### ISSUE TITLE
On r/programming

### ISSUE THREAD

**Issue by 12beesinatrenchcoat** [xNul/save-3rd-party-apps#15]
I've added a few not participating subreddits, adding the ones where I've seen at least one mod post saying they will not be closing or restricting the subreddit, not adding the ones where there's just been silence. 

There is one exception I'd like to ask about; [r/programming](https://www.reddit.com/r/programming/) features u/spez on the mod team, and so I suspect it's not participating, but there's been no formal post. I'm holding off on adding it now, but just wanted to open an issue to ask what the criteria for the list should be / for discussion.

(Also, some more subreddits have joined in! Although you're probably asleep right now. I hope you're getting some good rest!)

**Comment by xNul** [comment]
It seems like the general consensus is that pointing out which subs have decided to not participate would be harassment so I don't think I'll add a list of not participating subreddits.

Also, r/programming has decided to join! I'm so glad because I thought the same. Having an admin as the lead mod and *the CEO* as the second mod, I thought for sure they were not going to participate.

**Comment by 12beesinatrenchcoat** [comment]
Understandable - but on that note, what should be done with the [wiki page](https://github.com/xNul/save-3rd-party-apps/wiki/List-of-Not-Participating-Subreddits)? Keep it or delete it? 

Also very glad to see r/programming is participating!

**Comment by 12beesinatrenchcoat** [comment]
I've gone ahead and deleted the wiki page. (I've saved a copy on my own system, just in case, but I'm not putting it back up unless requested.)
